export default {
  items: [
    {
      name: "Green Apple",
      id: 1,
      color: "#0bff00",
      attributes: [],
      units: 0,
      price: 0.80,
    },
    {
      name: "Red Apple",
      id: 2,
      color: "#ff0000",
      attributes: [],
      units: 0,
      price: 1,
    },
    {
      name: "Orange",
      id: 3,
      color: "#ff9800",
      attributes: [],
      units: 0,
      price: 1,
    },
    {
      name: "Banana",
      id: 4,
      color: "#fff000",
      attributes: [],
      units: 0,
      price: 0.65,
    },
    {
      name: "Carrot",
      id: 5,
      color: "#ffce67",
      attributes: [],
      units: 0,
      price: 0.30,
    },
    {
      name: "Canned Soft Drink",
      id: 6,
      color: "#9e0f05",
      attributes: [],
      units: 0,
      price: 3,
    },
    {
      name: "Beans",
      id: 7,
      color: "#099065",
      attributes: [],
      units: 0,
      price: 3.20,
    },
    {
      name: "Potato",
      id: 8,
      color: "#e4dfa4",
      attributes: [],
      units: 0,
      price: 0.75,
    },
    {
      name: "Chocolate",
      id: 9,
      color: "#4e33c0",
      attributes: [],
      units: 0,
      price: 4,
    },
    {
      name: "Cereal",
      id: 10,
      color: "#d8c909",
      attributes: [],
      units: 0,
      price: 8,
    },
    {
      name: "Vegemite",
      id: 11,
      color: "#000000",
      attributes: [],
      units: 0,
      price: 7,
    },
    {
      name: "Instant Coffee",
      id: 12,
      color: "#442b00",
      attributes: [],
      units: 0,
      price: 11,
    },
  ],
  total: 0,
}